version: '3.7'
services:
    influxdb:
        image: quay.io/influxdb/influxdb:2.0.0-beta
        ports:
            - "9999:9999"
        volumes:
            - influxdb-storage:/root/.influxdbv2
        command:
            - --reporting-disabled
        restart: always

volumes:
    influxdb-storage: