version: '3.7'
services:
    influxdb:
        container_name: influxdb
        image: influxdb:2.2.0
        ports:
            - "8086:8086"
        volumes:
            - influxdb-storage:/root/.influxdbv2
        command:
            - --reporting-disabled
        restart: always

volumes:
    influxdb-storage:
